DROP TABLE IF EXISTS Reviews CASCADE;
DROP TABLE IF EXISTS Customers CASCADE;
DROP TABLE IF EXISTS Menu CASCADE;


CREATE TABLE Reviews (
	rid 			INTEGER PRIMARY KEY,
	review			VARCHAR(140),
	userid			INTEGER NOT NULL,
	rating			INTEGER NOT NULL
	FOREIGN KEY (userid) REFERENCES Users
);

CREATE TABLE Customers (
	userid 			INTEGER PRIMARY KEY,
	phone	 		INTEGER NOT NULL,
	points 			INTEGER NOT NULLs
);

CREATE TABLE Menu (
	name		VARCHAR(60) PRIMARY KEY,
	price		INTEGER NOT NULL,
	rid			INTEGER NOT NULL,
	FOREIGN KEY (rid) REFERENCES Restaurants
);